[features]
seeds = true
skip-lint = false
[programs.devnet]
quartz_prototype_v2 = "5Dxjir2yDi1aZAzgcnkEGmnLVop49DpNoru3c8DNAtcc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# wallet = "tests/keys/wallet-keypair.json"           # localnet test keypair
wallet = "~/.config/solana/id.json"       # personal keypair

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "idl/"
