[features]
seeds = true
skip-lint = false
[programs.localnet]
quartz_prototype_v2 = "57U6PNi6ymKcsTTsoFRC18iA4Nuaw6KdTz52NHqo3ENt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "tests/keys/wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
